version: 1

flags:
  - -trimpath
  - -tags=netgo

#goos: linux
#goarch: amd64

binary: binary-{{ .Os }}-{{ .Arch }}

ldflags:
  - "-X main.Version={{ .Env.VERSION }}"
  - "-X main.Commit={{ .Env.COMMIT }}"
  - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
  - "-X main.TreeState={{ .Env.TREE_STATE }}"